<html>
<title><?php echo $title ?></title>
<head>
</head>
<body style="background-color: lightgray">
<center><h3 style="background-image: url('custom/Frontpage/background.png')"> </h3></center>
<center>
 <table cellpadding="10">
   <tr>
     <td>
  <a href="https://swarm.workshop.perforce.com/users/matt_attaway">
    <img src="custom/Teampage/matt.png" width="253" height="419">
  </a>
</td>
<td>
  <a href="https://swarm.workshop.perforce.com/users/steph_turner">
    <img src="custom/Teampage/steph.jpg" width="260" height="419">
  </a>
</td>
<td>
  <a href="https://swarm.workshop.perforce.com/users/thomas_gray">
   <img src="custom/Teampage/thomas.png" width="253" height="419">
  </a>
</td>
<td>
  <a href="https://swarm.workshop.perforce.com/users/liz_lam">
  <img src="custom/Teampage/liz.jpg" width="260" :wheight="419">
 </a>
 </td>
 </tr>
 <tr>
 <td width="253">Matt Attaway
 </td>
 <td width="253">Steph Turner
 </td>
 <td width="253">Thomas Gray
 </td>
 <td width="253">Liz Lam
 </td>
 </tr>
 </table>
</center>
<br>
<center>
    <h5 style="padding-top: 15px; padding-bottom: 15px; color: white; background-image: url('custom/Frontpage/background.png')">
     Community Development Team
    </h5></center>
</body>
</html>
