<?php
$this->headTitle()->set('Activity');
?>

<div class="row-fluid">
    <div class="span4">
        <?php echo $this->projectsSidebar() ?>
    </div>
    <div class="span8">
        <br><br>
        <div class="row-fluid about-workshop">
            <div class="span12">
                <img src="/custom/Frontpage/jambox_select.png">
            </div>

            <div class="span8">

                <h2>Be a part of the team</h2>
                <div>
                    <p>Existing projects are here for you to explore.</p>
                    <p>Click on a project name to learn more.</p>
                    <p>Click "Join" to be a part of the team!</p>
                </div>
            </div>
        </div>

        <br>
        Not interested in any of the projects? Have a better idea? <a href="/projects/add/">Create your own</a>!
    </div>
</div>

<!---->
<!--<br><br>-->
<!--<img src="/custom/Frontpage/jambox_select.png">-->
<!--<br><br>-->